package com.example.hack2025

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import androidx.navigation.compose.rememberNavController
import com.example.hack2025.ui.navigation.AppNavigation
import com.example.hack2025.ui.theme.Hack2025Theme // Import your app's theme

/**
 * File Path: app/src/main/java/com/example/hack2025/MainActivity.kt
 *
 * The main entry point activity for the application. Sets up the Compose UI
 * including the theme and navigation host.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            // Apply your app's theme (generated by Android Studio)
            Hack2025Theme { // <-- Make sure this matches your theme name
                // A surface container using the 'background' color from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    // Create a NavController to handle screen transitions
                    val navController = rememberNavController()
                    // Set up the navigation graph defined in AppNavigation
                    AppNavigation(navController = navController)
                }
            }
        }
    }
}
